### ISSUE TITLE
Soil Rotation question

### ISSUE THREAD

**Issue by Hringingy** [Chakaa/cookie-garden-helper-reloaded#13]
Why does the soil rotation switch between Wood Chips/Clay? Unless I'm missing something, it would make more sense to have a Fertilizer/Clay rotation for passive plant effects and a Fertilizer/Wood Chips rotation for breeding new plant types.

**Comment by Chakaa** [comment]
Indeed, I think you have a good point there. I may have had a different idea in mind. I think I will allow for a selection of the combo used in the rotation. That will allow for both points of view.

**Comment by Chakaa** [comment]
I think this new version will cover your use case.
