### ISSUE TITLE
clean garden overwrites new seeds, if the new seed is on a tile that something else is supposed to be planted on.

### ISSUE THREAD

**Issue by Littleevo** [Chakaa/cookie-garden-helper-reloaded#29]
so a summary, i have saved a plot for growing brown mold, and harvesting dying plants was on. when a meddleweed got removed, a crumbspore took its place. it was young and was obviously taking over a meddleweed spot. 
the positions of the other meddleweeds weren't ideal at this point due to how they spread, so i selected clean garden, which is supposed to not harvest young new seeds, but it unearthed it anyway, making me lose my progress on that seed.
thankfully i had prepared a save before that, but please take a look at this. thank you.

**Comment by Littleevo** [comment]
i have just realized that this isn't a bug, but a feature. but imo it's not a great feature because of the reasons above.

**Comment by Chakaa** [comment]
its implement in version 1.6, thank you
