### ISSUE TITLE
Locked seeds can be planted through seedlist

### ISSUE THREAD

**Issue by TDarkShadow** [Chakaa/cookie-garden-helper-reloaded#3]
When using the auto-plant feature, you can let it plant seeds from the seed list, even when those (parent) seeds aren't unlocked yet.

**Comment by Chakaa** [comment]
Thank you, it should now be covered with the 1.3 version.
I added a new coloring orange when unlockable, red when not.
It checks if parents are unlocked.

**Comment by TDarkShadow** [comment]
Damn, you work fast. Thanks!
