### ISSUE TITLE
Avoid only "large" buffs if the quantity of empty plots are small

### ISSUE THREAD

**Issue by be5invis** [Chakaa/cookie-garden-helper-reloaded#36]
With a lot of Clovers, "Frenzy" buff could usually stack for a very long time, which effectively blocks replanting.
There could be an alternative option for the "avoid buffs" switch, which only blocks buffs that is sufficiently large (like > 10x).

**Comment by Chakaa** [comment]
You should be able to use the "Check CpS mult" option, setting the multiplier at 10 just below, and setting the avoid buff off.
It will only replant if your global multiplier is lower or equal your setting.
