### ISSUE TITLE
When I drop the mod in mods/local folder and restart the game, it is stuck on loading

### ISSUE THREAD

**Issue by leo91000** [Chakaa/cookie-garden-helper-reloaded#5]
Hey,

First of all, thanks for this mod.

I have a problem after installing the mod, i am stuck on loading like the screenshot after.

How can I solve this ?

![image](https://user-images.githubusercontent.com/1354510/135423390-c986970a-6506-4a7c-a8e4-47dcdb9970d1.png)

**Comment by Chakaa** [comment]
#6 Solved it by reverting a value in info.txt

**Comment by leo91000** [comment]
Thanks !

**Comment by Chakaa** [comment]
PR solved the issue
