### ISSUE TITLE
Recipes only show one seed

### ISSUE THREAD

**Issue by jennyl** [Chakaa/cookie-garden-helper-reloaded#8]
hi

im on the latest version (1.4.3), but i downloaded the mod on september 28, whichever version that was

not sure if this was intended because i don't know all the seed combinations (only aware of the ones on the wiki and from the horticookie mod)

![image](https://user-images.githubusercontent.com/4051215/135697311-79be7eca-08b0-48f5-8992-3643eb05ca66.png)

All the other plots show a variation of this image, where it's only one seed in a row or two rows

here's another example recipe
![image](https://user-images.githubusercontent.com/4051215/135697390-ca0e8771-fbf3-4e59-821e-a2153f7ab845.png)

**Comment by Chakaa** [comment]
Hi,

Good find. There was indeed an issue at farm level 3 and 4.

Thank you.
